### ISSUE TITLE
iptables 规则不够合理

### ISSUE THREAD

**Issue by wangliangliang2** [kiddin9/openwrt-adguardhome#2]
以下四个地方的防火墙规则不合理，应该使用-I 而不是使用-A
使用 -A会导致dns流量仍然走dnsmasq ，-I 由于把规则插入到dnsmasq之上所以能正确的将流量导入到adguardhome上。

[不合理地方](https://github.com/kiddin9/openwrt-adguardhome/blob/master/luci-app-adguardhome/root/etc/init.d/AdGuardHome#L77)
[不合理地方](https://github.com/kiddin9/openwrt-adguardhome/blob/master/luci-app-adguardhome/root/etc/init.d/AdGuardHome#L79)
[不合理地方](https://github.com/kiddin9/openwrt-adguardhome/blob/master/luci-app-adguardhome/root/etc/init.d/AdGuardHome#L90)
[不合理地方](https://github.com/kiddin9/openwrt-adguardhome/blob/master/luci-app-adguardhome/root/etc/init.d/AdGuardHome#L92)

另外，由于我自己也在用着 由 https://supes.top 编译的固件，希望在改了这几处后，并且更新固件后，能帮忙@ 我下，我好更新下固件

**Comment by kiddin9** [comment]
已更新. @wangliangliang2
